filebeat.inputs:
- type: docker
  combine_partial: true
  containers:
    path: "/usr/share/dockerlogs/data"
    stream: "stdout"
    ids: 
      - "*"
    cri.parse_flags: true
    combine_partial: true
    exclude_files: ['\.gz$']
    

processors:
- decode_json_fields:
    fields: ["log","message"]
    target: ""
    overwrite_keys: true
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
    

# Output
output.elasticsearch:
  hosts: ["https://todov100.es.ap-south-1.aws.elastic-cloud.com:9243"]
  username: "elastic"
  password: "M1kbwNCDDWLhyzbokDXqPt6E"
  index: "demo"
  pipeline: "demo-pipeline"

setup:
  template.enabled: false
  ilm.enabled: false




# Filebeat specific
# logging.level: error
# logging.to_files: false
# logging.to_syslog: false
# loggins.metrice.enabled: false
# logging.files:
#   path: /var/log/filebeat
#   name: filebeat
#   keepfiles: 7
#   permissions: 0644
# ssl.verification_mode: none
