version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todov100/todobackend:latest
    ports:
     - "3000:3000"
  filebeat:
    hostname: filebeat
    build:
      context: filebeat
      dockerfile: Dockerfile
    image: todov100/filebeats:latest
    volumes:
     - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
     - "/var/run/docker.sock:/var/run/docker.sock"

      