name: toDoBackend Docker
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dockerLogin
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: byterider/todoBackend:latest

