name: toDoBackend Docker
on:
  push:
    branches: [ frontend ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
      - name: dockerLogin
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: todov100/todobackend:latest
      - run: docker build --tag todo-app:latest .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1
          image: todo-app:latest
      - name: Moving build to artifacts directory
        run: |
             ls -al
             ecs-cli --version
             chmod +x ./rundeck.sh
             ./rundeck.sh     

