name: toDoBackend Docker
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Frontend UI
        uses: actions/checkout@v2
        with:
          repository: kingavatar/todoOnline
          path: todoOnline
        run: |
          npm install
          npm run build  
          ls
          pwd    
      - name: dockerLogin
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: todov100/todobackend:latest

